version: '2.1'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp
    ports:
      - "3306"
    healthcheck:
      test: "exit 0"

  app:
    build: .
    command: bash -c "rails db:migrate && rails s"
    ports:
      - "3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: root
      DB_NAME: myapp
      DB_PASSWORD: password
      DB_HOST: db

  server:
    image: nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      - app
